CREATE TABLE PESSOAS
(
    NOME            VARCHAR(255) NOT NULL PRIMARY KEY,
    CPF             NUMERIC(11)  NOT NULL,
    DATA_NASCIMENTO DATE         NOT NULL,
    SEXO            CHAR,
    EMAIL           VARCHAR(320),
    NATURALIDADE    VARCHAR(255),
    NACIONALIDADE   VARCHAR(255)
);

